### ISSUE TITLE
 rss link support to subscribe

### ISSUE THREAD

**Issue by AsJoy** [Geospace/blog.geographer.fr#19]

**Comment by Geospace** [comment]
Good idea! I totally forgot that RSS existed...

This should not be complicated to add thanks to Pelican. Will take a look at it as soon as possible.

**Comment by Geospace** [comment]
https://github.com/Geospace/blog.geographer.fr/pull/20 implements it. There is now an RSS link in the website's footer.

Feel free to open another issue if the RSS feed does not work as expected.
